# Generated by Django 4.2.8 on 2023-12-27 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
        ("booths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="last_updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player",
                to="registration.account",
            ),
        ),
    ]
