# Generated by Django 4.2.8 on 2024-02-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booths", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="player", name="records",),
        migrations.AddField(
            model_name="records",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player",
                to="booths.player",
            ),
        ),
    ]
