# Generated by Django 4.2.8 on 2024-01-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booths", "0002_player_last_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="teletag",
            field=models.CharField(blank=True, db_column="teletag", null=True),
        ),
    ]
