# Generated by Django 4.2.8 on 2024-01-04 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booths", "0003_player_teletag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="last_updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
