# Generated by Django 4.2.8 on 2024-02-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booths", "0003_remove_player_organization_player_education_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="email",
            field=models.CharField(
                blank=True, db_column="email", max_length=50, null=True
            ),
        ),
    ]
